image: debian:buster

pages:
  script:
    - apt-get update && apt-get -y install python3 python3-setuptools python3-pip nodejs
      npm git rsync
    - pip3 install pytest-check-links black sphinx flit doit
    - npm install --global yarn
    - doit
    - rsync -a --copy-links app/ public/
  artifacts:
    paths:
      - public/
